export const CATEGORIES = [
  { id: '1', name: 'Masala Powders', icon: 'https://aishwaryamoils.com/cdn/shop/files/Chilli_Powder_1.jpg?v=1737530090&width=300' },
  { id: '2', name: 'Oils', icon: 'https://aishwaryamoils.com/cdn/shop/files/Coconut_Oil_1.jpg?v=1737530216&width=300' },
  { id: '3', name: 'Ghee', icon: 'https://aishwaryamoils.com/cdn/shop/files/Buffalo_Ghee.jpg?v=1737530156&width=300' },
  { id: '4', name: 'Snacks', icon: 'https://aishwaryamoils.com/cdn/shop/files/Almonds.jpg?v=1737530126&width=300' },
  { id: '5', name: 'Millets & Rice', icon: 'https://aishwaryamoils.com/cdn/shop/files/Black-Kavuni-Rice-600x600.jpg?v=1737530178&width=300' },
  { id: '6', name: 'Pickles', icon: 'https://aishwaryamoils.com/cdn/shop/files/Castor_Oil_1.jpg?v=1737530195&width=300' },
];

export const BANNERS = [
  {
    id: '1',
    title: 'Fresh Masala Powders',
    subtitle: 'Stone-ground, pure & aromatic',
    image: 'https://aishwaryamoils.com/cdn/shop/files/Chilli_Powder_1.jpg?v=1737530090&width=800',
    color: '#108474',
  },
  {
    id: '2',
    title: 'Wood Pressed Oils',
    subtitle: 'Traditional cold-pressed goodness',
    image: 'https://aishwaryamoils.com/cdn/shop/files/Coconut_Oil_1.jpg?v=1737530216&width=800',
    color: '#D4A373',
  },
  {
    id: '3',
    title: 'Premium Ghee',
    subtitle: 'Pure & farm-fresh quality',
    image: 'https://aishwaryamoils.com/cdn/shop/files/Buffalo_Ghee.jpg?v=1737530156&width=800',
    color: '#E76F51',
  },
  {
    id: '4',
    title: 'Crunchy Dry Fruits',
    subtitle: 'Handpicked almonds, cashews & more',
    image: 'https://aishwaryamoils.com/cdn/shop/files/Almonds.jpg?v=1737530126&width=800',
    color: '#8B5E3C',
  },
  {
    id: '5',
    title: 'Organic Millets & Rice',
    subtitle: 'Nutritious & naturally grown grains',
    image: 'https://aishwaryamoils.com/cdn/shop/files/Black-Kavuni-Rice-600x600.jpg?v=1737530178&width=800',
    color: '#6B8E23',
  },
  {
    id: '6',
    title: 'Traditional Health Malts',
    subtitle: 'Time-tested recipes for wellness',
    image: 'https://aishwaryamoils.com/cdn/shop/files/Beetroot_Malt_1.jpg?v=1737530149&width=800',
    color: '#9B2335',
  },
];

export const FEATURED_PRODUCTS = [
  {
    id: '1',
    name: 'Chilli Powder',
    weight: '150g',
    price: 119,
    originalPrice: 149,
    rating: 4.5,
    reviews: 42,
    image: 'https://aishwaryamoils.com/cdn/shop/files/Chilli_Powder_1.jpg?v=1737530090&width=400',
    category: 'Masala Powders',
    badge: 'Bestseller',
  },
  {
    id: '2',
    name: 'Coconut Oil',
    weight: '1 Litre',
    price: 529,
    originalPrice: 649,
    rating: 4.8,
    reviews: 128,
    image: 'https://aishwaryamoils.com/cdn/shop/files/Coconut_Oil_1.jpg?v=1737530216&width=400',
    category: 'Oils',
    badge: 'Popular',
  },
  {
    id: '3',
    name: 'Buffalo Ghee',
    weight: '500ml',
    price: 649,
    originalPrice: 799,
    rating: 4.7,
    reviews: 89,
    image: 'https://aishwaryamoils.com/cdn/shop/files/Buffalo_Ghee.jpg?v=1737530156&width=400',
    category: 'Ghee',
    badge: null,
  },
  {
    id: '4',
    name: 'Almond Oil',
    weight: '100ml',
    price: 399,
    originalPrice: 499,
    rating: 4.6,
    reviews: 35,
    image: 'https://aishwaryamoils.com/cdn/shop/files/Almond_Oil_35060ea5-a910-49d1-9317-f63628a241a0.jpg?v=1737530119&width=400',
    category: 'Oils',
    badge: 'New',
  },
];

export const BEST_SELLERS = [
  {
    id: '5',
    name: 'Cashew Nuts',
    weight: '150g',
    price: 199,
    originalPrice: 249,
    rating: 4.9,
    reviews: 215,
    image: 'https://aishwaryamoils.com/cdn/shop/files/Cashew.jpg?v=1737530195&width=400',
    category: 'Snacks',
  },
  {
    id: '6',
    name: 'Black Kavuni Rice',
    weight: '1Kg',
    price: 249,
    originalPrice: 299,
    rating: 4.4,
    reviews: 67,
    image: 'https://aishwaryamoils.com/cdn/shop/files/Black-Kavuni-Rice-600x600.jpg?v=1737530178&width=400',
    category: 'Millets & Rice',
  },
  {
    id: '7',
    name: 'Virgin Coconut Oil',
    weight: '250ml',
    price: 299,
    originalPrice: 379,
    rating: 4.8,
    reviews: 156,
    image: 'https://aishwaryamoils.com/cdn/shop/files/Virgin_Coconut_Oil_9a205c9f-4cb9-4a97-b73f-d12d6729dd6a.jpg?v=1737530302&width=400',
    category: 'Oils',
  },
  {
    id: '8',
    name: 'Charcoal Soap',
    weight: '100g',
    price: 119,
    originalPrice: 149,
    rating: 4.3,
    reviews: 48,
    image: 'https://aishwaryamoils.com/cdn/shop/files/Charcoal_Soap.jpg?v=1737530198&width=400',
    category: 'Skin & Hair Care',
  },
  {
    id: '9',
    name: 'Beetroot Malt',
    weight: '250g',
    price: 379,
    originalPrice: 449,
    rating: 4.5,
    reviews: 32,
    image: 'https://aishwaryamoils.com/cdn/shop/files/Beetroot_Malt_1.jpg?v=1737530149&width=400',
    category: 'Traditional Foods',
  },
  {
    id: '10',
    name: 'Black Raisins',
    weight: '150g',
    price: 119,
    originalPrice: 159,
    rating: 4.6,
    reviews: 73,
    image: 'https://aishwaryamoils.com/cdn/shop/files/Black_Raisin_1.jpg?v=1737530170&width=400',
    category: 'Snacks',
  },
];

export const DRAWER_MENU_ITEMS = [
  { id: '1', label: 'Home', icon: 'home', screen: 'HomeScreen' },
  { id: '2', label: 'Shop All', icon: 'grid', screen: 'ShopAll' },
  { id: '3', label: 'Masala Powders', icon: 'sun', screen: 'Category' },
  { id: '4', label: 'Oils & Ghee', icon: 'droplet', screen: 'Category' },
  { id: '5', label: 'Traditional Foods', icon: 'coffee', screen: 'Category' },
  { id: '6', label: 'Millets & Rice', icon: 'package', screen: 'Category' },
  { id: '7', label: 'Pickles & Podi', icon: 'archive', screen: 'Category' },
  { id: '8', label: 'Skin & Hair Care', icon: 'heart', screen: 'Category' },
  { id: '9', label: 'Value Packs', icon: 'gift', screen: 'ValuePacks' },
  { id: '10', label: 'Our Story', icon: 'book-open', screen: 'OurStory' },
  { id: '11', label: 'Contact Us', icon: 'phone', screen: 'Contact' },
  { id: '12', label: 'Track Order', icon: 'truck', screen: 'TrackOrder' },
];
